/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/home.vue')['default']
    Manage: typeof import('./src/components/manage.vue')['default']
    Medicine: typeof import('./src/components/item/medicine.vue')['default']
    Mine: typeof import('./src/components/mine.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutCollapse: typeof import('@nutui/nutui-taro')['Collapse']
    NutCollapseItem: typeof import('@nutui/nutui-taro')['CollapseItem']
    NutMenu: typeof import('@nutui/nutui-taro')['Menu']
    NutMenuItem: typeof import('@nutui/nutui-taro')['MenuItem']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    Plan: typeof import('./src/components/item/plan.vue')['default']
  }
}
